### ISSUE TITLE
homework1

### ISSUE THREAD

**Issue by codepictor** [Ivanova475/cplusplus-tasks#1]
https://github.com/Ivanova475/cplusplus-tasks/blob/f082cc6566826ad04b760fe46d55b4cb25c20ae4/Matrix/Matrix/matrix.h#L13
Совсем не обязательно делать эту штуку другом класса

https://github.com/Ivanova475/cplusplus-tasks/blob/f082cc6566826ad04b760fe46d55b4cb25c20ae4/Matrix/Matrix/matrix.h#L18
не хватает строки virtual ~Matrix() = default();

https://github.com/Ivanova475/cplusplus-tasks/blob/f082cc6566826ad04b760fe46d55b4cb25c20ae4/Matrix/Matrix/matrix.cpp#L6
табуляция вместо пробелов (и ещё много таких мест)

https://github.com/Ivanova475/cplusplus-tasks/blob/f082cc6566826ad04b760fe46d55b4cb25c20ae4/Matrix/Matrix/matrix.cpp#L115
с точки зрения производительности здесь лучше "\n", а не std::endl

https://github.com/Ivanova475/cplusplus-tasks/blob/f082cc6566826ad04b760fe46d55b4cb25c20ae4/Matrix/Matrix/matrix.cpp#L2
после инклюдов здесь оставлено 2 пустые строки, а в других файлах - 3

https://github.com/Ivanova475/cplusplus-tasks/blob/f082cc6566826ad04b760fe46d55b4cb25c20ae4/Matrix/Matrix/matrix.cpp#L66
Ошибка. Если GetWidth() != rhs.GetHeight(), то вернётся мусорная матрица

**Comment by codepictor** [comment]
https://github.com/Ivanova475/cplusplus-tasks/blob/964da84ee899a91d6b9f4e87652bc6ef4d375a83/Matrix/Matrix/matrix.cpp#L71
Этот else лучше убрать, т.е. оставить весь код, который в else-блоке, но убрать сам else

https://github.com/Ivanova475/cplusplus-tasks/blob/964da84ee899a91d6b9f4e87652bc6ef4d375a83/Matrix/Matrix/matrix.h#L23
мало пробелов, нужно хотя бы на 4 больше, а ещё лучше, чтобы этот кусочек выглядел так:
void SetValue(const size_t height_index, const size_t width_index,
                       const int value);

**Comment by codepictor** [comment]
https://github.com/Ivanova475/cplusplus-tasks/blob/3f66e762d14934aa589effdf5a48c7ad8a9b27ce/Matrix/Matrix/matrix.cpp#L70
после этой строчки пробельная строка очень не помешала бы

**Comment by codepictor** [comment]
https://github.com/Ivanova475/cplusplus-tasks/blob/3f66e762d14934aa589effdf5a48c7ad8a9b27ce/Matrix/Matrix/matrix.h#L23
ой, вот тут я не заметил, что пробелы убрались
в общем, сторая строчка должна начинаться под открывающей скобкой (
но не прям под ней, а на один символ справа

**Comment by codepictor** [comment]
https://github.com/Ivanova475/cplusplus-tasks/blob/8d5d696a125d6293e799988f424211e2b90779e8/Matrix/Matrix/matrix.cpp#L89
Здесь не должно быть пустой строки

**Comment by gitluup** [comment]
OK

**Comment by codepictor** [comment]
OK
